services:

  dev-postgres:
    image: postgres:latest
    container_name: dev-postgres
    hostname: dev-postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - PGTZ=Asia/Tokyo
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - dev-postgres-volume:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 18080:80
    volumes:
      - pgadmin4-volume:/var/lib/pgadmin

volumes:
  dev-postgres-volume:
    name: dev-postgres-volume
    driver: local
  pgadmin4-volume:
    name: pgadmin4-volume
    driver: local

