services:
  dev-postgres:
    image: postgres:15.7
    container_name: dev-postgres
    hostname: dev-postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - PGTZ=Asia/Tokyo
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - dev-postgres-volume:/var/lib/postgresql/data

volumes:
  dev-postgres-volume:
    name: dev-postgres-volume
    driver: local

networks:
  default:
    name: develop-network
    external: true
